name: github actions

on: [push]

jobs:
  github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: pwd
        run: |
         pwd
         ls -a
      - name: simple js actions
        id: anil
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: ANIL
      - name: time
        run: echo "{{steps.anil.outputs.time}}"
